"""Add is_active column to User

Revision ID: 3a94da69b688
Revises: 6664325c78de
Create Date: 2025-06-18 00:18:45.923044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a94da69b688'
down_revision = '6664325c78de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
